### ISSUE TITLE
Potential false positive on Motorola Moto E4 (Android version 7.1.1.1) 

### ISSUE THREAD

**Issue by JordanePeters54400** [tam892007/Xamarin.Forms.RootCheck#1]
We got a positive rootcheck result with the method IsDeviceRooted() with the following device and android version: Motorola Moto E4 (Android version 7.1.1.1). Unfortunately, we do not have access to the device but the device holder says that the device is not rooted. We did not succeed in reproducing the issue. Do you have any clue if the Motorola family would have a specific configuration which could trigger the rootcheck ?

**Comment by tam892007** [comment]
Hi,
Apology for replying late since it's not maintained for a while. One possibility is the check for BusyBox binary, as some manufacturers include it by default. You may want to get the code and comment out this line to verify.

![image](https://user-images.githubusercontent.com/10487641/134102460-f644e5be-66a1-4f0e-a7da-9eb491eed3c3.png)

Additionally, I highly recommend you to look into source of RootBeer library, which this library based on:

https://github.com/scottyab/rootbeer/blob/master/rootbeerlib/src/main/java/com/scottyab/rootbeer/RootBeer.java

Thanks,
Tam.
